[package]
name = "artemis"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }

[addresses]
my_addrx = "0x8ee95d61e06fc6feb03f0a56b425c9ba7ae5ae5dd9f18c6adc2c00c8a8bbff53"
std = "0x1"